###### 开启 Spring Boot 对于 Bean id 的 Override 机制
spring:
  main:
    allow-bean-definition-overriding: true
  scan:
    base-packages: com.wwangya.witmed
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka