###### 配置注册中心启动端口号
server:
  port: 9999
spring:
  ###### 配置项目应用名
  application:
    name: LuckyWitmed-register
  ###### 配置开启 Spring Boot 对于 Bean ID 的 Override 机制
  main:
    allow-bean-definition-overriding: true
###### 配置 Eureka Server 信息
eureka:
  ###### 配置注册中心主机名，该主机名可用于其他应用确定和连接注册中心
  instance:
    hostname: localhost
  client:
    ###### 由于本项目是注册中心项目，因此禁止本项目的服务也向注册中心中进行注册
    register-with-eureka: false
    ###### 对于 Spring Cloud 来说，是允许多个注册中心存在的，那么这些注册中心之间就会交换注册信息
    ###### 这样的好处是，当注册的服务过多时，就能够分担注册压力，
    ###### 但是本项目就一个注册中，因此禁止去其他注册中心发现服务
    fetch-registry: false
    ###### 暴露注册中心连接地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka